version: '3.8'

services:
  sqlserver:
    build:
      context: .
    image: my_sql_server_image 
    container_name: my_sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express 
    ports:
      - "1433:1433"
